In [1]:
#Importing libraries and opening train and test data
import pandas as pd
import numpy as np
import matplotlib as mpl
data = pd.read_csv('C:/Users/aashw/Downloads/music_train.csv')
test_data = pd.read_csv('C:/Users/aashw/Downloads/music_test.csv')

In [2]:
data

id  release_date    dating  violence  world/life  night/time  \
0          0        2014.0  0.001049  0.000254    0.078057    0.282523   
1          1        1962.0  0.059132       NaN         NaN    0.001836   
2          2        1969.0  0.027451  0.085989    0.039760    0.001288   
3          3        2004.0  0.050993       NaN    0.000000    0.000477   
4          4        1992.0  0.000551  0.028702    0.000000    0.069748   
...      ...           ...       ...       ...         ...         ...   
17738  17738        2011.0  0.006589  0.000000    0.021678    0.000000   
17739  17739        2002.0  0.008281       NaN    0.071316    0.025514   
17740  17740        1982.0  0.000710  0.388212    0.000615    0.078012   
17741  17741           NaN  0.027210  0.117397    0.004522    0.296837   
17742  17742        1992.0  0.000120  0.002267    0.439454    0.000999   

       shake the audience  family/gospel  romantic  communication  ...  \
0                0.000000       0.000654  1.109899       3.484935  ...   
1                0.000737       0.000000  0.758840       0.000000  ...   
2                0.001424       0.000857  0.545408       0.016914  ...   
3                0.008157       0.002800  0.000000       0.003703  ...   
4                0.008735       0.000625  0.014364       0.253022  ...   
...                   ...            ...       ...            ...  ...   
17738            0.007656       0.000552  0.000478       0.004078  ...   
17739            0.130170       0.013863  0.016706       0.000000  ...   
17740            0.002473       0.000000  2.024262       0.998057  ...   
17741            0.002955       0.002310  0.000000       0.431139  ...   
17742            0.015221       0.071824  0.023428            NaN  ...   

       feelings  danceability  loudness  acousticness  instrumentalness  \
0      0.001021      0.673433  0.753102      0.002560          0.001046   
1      0.001697      0.690740  0.678925      0.785480          0.001009   
2      0.000000      0.186294  0.404628      0.890527          0.060886   
3      0.067061      0.499643  0.685085      0.640129          0.163850   
4      0.000000      0.407141  0.616982      0.030576               NaN   
...         ...           ...       ...           ...               ...   
17738  0.265363      0.699730  0.753779      0.510676          0.000624   
17739  0.001289      0.758641  0.716034           NaN          0.000000   
17740  0.003411      0.512652  0.732854      0.017187          0.491014   
17741  0.000000      0.594225  0.754684      0.005137          0.000091   
17742       NaN      0.465397  0.735680      0.649489               NaN   

        valence     energy       age  genre  topic  
0      0.040567  48.364265  0.085714      4    2.0  
1      0.743203  28.200609  0.828571      1    7.0  
2      0.093003  13.145639  0.728571      4    NaN  
3      0.648084  62.663152  0.228571      0    5.0  
4           NaN  48.641741  0.400000      1    1.0  
...         ...        ...       ...    ...    ...  
17738  0.271493  74.876372  0.128571      4    3.0  
17739  0.915961  50.097257  0.257143      5    3.0  
17740  0.606948  92.972488  0.542857      0    6.0  
17741  0.456820  74.079139  0.557143      4    2.0  
17742  0.466926  54.085364  0.400000      4    7.0  

[17743 rows x 27 columns]

In [3]:
data.describe()

id  release_date        dating      violence    world/life  \
count  17743.000000  16867.000000  16880.000000  16865.000000  16815.000000   
mean    8871.000000   1989.947709      0.044267      0.145387      0.148644   
std     5122.107249     18.624231      0.158097      0.225202      0.220580   
min        0.000000   1950.000000      0.000000      0.000000      0.000000   
25%     4435.500000   1975.000000      0.000427      0.001486      0.001752   
50%     8871.000000   1991.000000      0.001606      0.004364      0.021138   
75%    13306.500000   2007.000000      0.005910      0.253201      0.242380   
max    17742.000000   2019.000000      1.000000      1.000000      1.000000   

         night/time  shake the audience  family/gospel      romantic  \
count  16835.000000        16828.000000   16804.000000  16841.000000   
mean       0.078145            0.042176       0.044730      0.695758   
std        0.180491            0.158760       0.157988      1.772994   
min        0.000000            0.000000       0.000000      0.000000   
25%        0.000705            0.000537       0.000987      0.006163   
50%        0.002307            0.001728       0.002596      0.021249   
75%        0.066496            0.013187       0.012928      0.435014   
max        1.000000            1.000000       1.000000     10.000000   

       communication  ...      feelings  danceability      loudness  \
count   16836.000000  ...  16814.000000  16878.000000  16901.000000   
mean        1.037052  ...      0.053245      0.547723      0.674296   
std         1.795863  ...      0.163274      0.189198      0.134556   
min         0.000000  ...      0.000000      0.000000      0.000000   
25%         0.015231  ...      0.000637      0.425374      0.604900   
50%         0.045014  ...      0.002046      0.551020      0.690477   
75%         1.512255  ...      0.033031      0.672999      0.761244   
max        10.000000  ...      1.000000      1.000000      1.000000   

       acousticness  instrumentalness       valence        energy  \
count  16843.000000      16831.000000  16885.000000  16894.000000   
mean       0.361842          0.099289      0.524999     55.966998   
std        0.338724          0.246229      0.264711     25.844732   
min        0.000000          0.000000      0.000000      0.000000   
25%        0.038948          0.000000      0.311373     35.759715   
50%        0.250711          0.001081      0.527245     56.730710   
75%        0.676488          0.010833      0.743153     77.570420   
max        1.000000          1.000000      1.000000    100.000000   

                age         genre         topic  
count  16874.000000  17743.000000  16869.000000  
mean       0.437873      2.946965      4.504239  
std        0.266335      2.036571      2.011482  
min        0.014286      0.000000      0.000000  
25%        0.200000      1.000000      3.000000  
50%        0.435714      3.000000      5.000000  
75%        0.657143      4.000000      6.000000  
max        1.000000      6.000000      7.000000  

[8 rows x 27 columns]

In [4]:
#Checking NaN values in each column
data.isna().sum()

id                            0
release_date                876
dating                      863
violence                    878
world/life                  928
night/time                  908
shake the audience          915
family/gospel               939
romantic                    902
communication               907
obscene                     876
music                       836
movement/places             885
light/visual perceptions    872
family/spiritual            894
like/girls                  891
sadness                     910
feelings                    929
danceability                865
loudness                    842
acousticness                900
instrumentalness            912
valence                     858
energy                      849
age                         869
genre                         0
topic                       874
dtype: int64

In [5]:
#Dropping rows
data.dropna(axis = 0, thresh = 10, inplace = True)

In [6]:
#Calculating the mean of parameters 'genre-wise'
df = data.groupby('genre', dropna = False)
df.mean()

id  release_date    dating  violence  world/life  night/time  \
genre                                                                          
0      9012.867365   1988.946252  0.051022  0.161214    0.127721    0.078859   
1      9048.573146   1985.681186  0.036619  0.096856    0.150804    0.078383   
2      8869.261346   2008.897181  0.098024  0.179640    0.146738    0.118738   
3      8825.007095   1988.055360  0.040732  0.133906    0.158847    0.074533   
4      8757.575122   1988.274194  0.036434  0.122692    0.137199    0.066793   
5      8799.226332   1997.543906  0.056527  0.178907    0.186555    0.090191   
6      8753.299528   1991.902002  0.042602  0.212065    0.155688    0.081815   

       shake the audience  family/gospel  romantic  communication  ...  \
genre                                                              ...   
0                0.038977       0.047670  0.717796       0.961259  ...   
1                0.033949       0.043301  0.740702       1.026532  ...   
2                0.112261       0.104258  0.986468       1.538351  ...   
3                0.040448       0.045305  0.815681       0.920589  ...   
4                0.032439       0.030840  0.592335       1.055521  ...   
5                0.058657       0.058757  0.638709       1.120383  ...   
6                0.046749       0.042675  0.634688       1.033821  ...   

        sadness  feelings  danceability  loudness  acousticness  \
genre                                                             
0      0.127674  0.054543      0.498042  0.673533      0.386709   
1      0.171357  0.046600      0.553435  0.642986      0.473609   
2      0.123228  0.113123      0.723353  0.720810      0.226379   
3      0.141290  0.049884      0.529966  0.618622      0.519502   
4      0.149039  0.043428      0.537924  0.693308      0.320656   
5      0.110146  0.066636      0.709225  0.688686      0.215245   
6      0.147537  0.056912      0.484050  0.716816      0.229646   

       instrumentalness   valence     energy       age     topic  
genre                                                             
0              0.106518  0.530206  56.980145  0.449778  4.408321  
1              0.038631  0.527117  45.389658  0.498559  4.469482  
2              0.112309  0.601287  69.000531  0.195951  3.447195  
3              0.240326  0.462349  45.302411  0.463884  4.443619  
4              0.058745  0.522829  59.148604  0.458416  4.535967  
5              0.079159  0.686197  58.214382  0.333993  4.580239  
6              0.117036  0.458184  69.145235  0.410675  4.881546  

[7 rows x 26 columns]

In [7]:
#Filling NaN values with average values
data = data.fillna(data.mean())

In [8]:
data

id  release_date    dating  violence  world/life  night/time  \
0          0   2014.000000  0.001049  0.000254    0.078057    0.282523   
1          1   1962.000000  0.059132  0.145387    0.148644    0.001836   
2          2   1969.000000  0.027451  0.085989    0.039760    0.001288   
3          3   2004.000000  0.050993  0.145387    0.000000    0.000477   
4          4   1992.000000  0.000551  0.028702    0.000000    0.069748   
...      ...           ...       ...       ...         ...         ...   
17738  17738   2011.000000  0.006589  0.000000    0.021678    0.000000   
17739  17739   2002.000000  0.008281  0.145387    0.071316    0.025514   
17740  17740   1982.000000  0.000710  0.388212    0.000615    0.078012   
17741  17741   1989.947709  0.027210  0.117397    0.004522    0.296837   
17742  17742   1992.000000  0.000120  0.002267    0.439454    0.000999   

       shake the audience  family/gospel  romantic  communication  ...  \
0                0.000000       0.000654  1.109899       3.484935  ...   
1                0.000737       0.000000  0.758840       0.000000  ...   
2                0.001424       0.000857  0.545408       0.016914  ...   
3                0.008157       0.002800  0.000000       0.003703  ...   
4                0.008735       0.000625  0.014364       0.253022  ...   
...                   ...            ...       ...            ...  ...   
17738            0.007656       0.000552  0.000478       0.004078  ...   
17739            0.130170       0.013863  0.016706       0.000000  ...   
17740            0.002473       0.000000  2.024262       0.998057  ...   
17741            0.002955       0.002310  0.000000       0.431139  ...   
17742            0.015221       0.071824  0.023428       1.037052  ...   

       feelings  danceability  loudness  acousticness  instrumentalness  \
0      0.001021      0.673433  0.753102      0.002560          0.001046   
1      0.001697      0.690740  0.678925      0.785480          0.001009   
2      0.000000      0.186294  0.404628      0.890527          0.060886   
3      0.067061      0.499643  0.685085      0.640129          0.163850   
4      0.000000      0.407141  0.616982      0.030576          0.099289   
...         ...           ...       ...           ...               ...   
17738  0.265363      0.699730  0.753779      0.510676          0.000624   
17739  0.001289      0.758641  0.716034      0.361842          0.000000   
17740  0.003411      0.512652  0.732854      0.017187          0.491014   
17741  0.000000      0.594225  0.754684      0.005137          0.000091   
17742  0.053245      0.465397  0.735680      0.649489          0.099289   

        valence     energy       age  genre     topic  
0      0.040567  48.364265  0.085714      4  2.000000  
1      0.743203  28.200609  0.828571      1  7.000000  
2      0.093003  13.145639  0.728571      4  4.504239  
3      0.648084  62.663152  0.228571      0  5.000000  
4      0.524999  48.641741  0.400000      1  1.000000  
...         ...        ...       ...    ...       ...  
17738  0.271493  74.876372  0.128571      4  3.000000  
17739  0.915961  50.097257  0.257143      5  3.000000  
17740  0.606948  92.972488  0.542857      0  6.000000  
17741  0.456820  74.079139  0.557143      4  2.000000  
17742  0.466926  54.085364  0.400000      4  7.000000  

[17743 rows x 27 columns]

In [9]:
#Rounding off release_date and topic to make more sense
data['release_date'] = data['release_date'].apply(lambda x : round(x,0))
data['topic'] = data['topic'].apply(lambda x : round(x,0))
data

id  release_date    dating  violence  world/life  night/time  \
0          0        2014.0  0.001049  0.000254    0.078057    0.282523   
1          1        1962.0  0.059132  0.145387    0.148644    0.001836   
2          2        1969.0  0.027451  0.085989    0.039760    0.001288   
3          3        2004.0  0.050993  0.145387    0.000000    0.000477   
4          4        1992.0  0.000551  0.028702    0.000000    0.069748   
...      ...           ...       ...       ...         ...         ...   
17738  17738        2011.0  0.006589  0.000000    0.021678    0.000000   
17739  17739        2002.0  0.008281  0.145387    0.071316    0.025514   
17740  17740        1982.0  0.000710  0.388212    0.000615    0.078012   
17741  17741        1990.0  0.027210  0.117397    0.004522    0.296837   
17742  17742        1992.0  0.000120  0.002267    0.439454    0.000999   

       shake the audience  family/gospel  romantic  communication  ...  \
0                0.000000       0.000654  1.109899       3.484935  ...   
1                0.000737       0.000000  0.758840       0.000000  ...   
2                0.001424       0.000857  0.545408       0.016914  ...   
3                0.008157       0.002800  0.000000       0.003703  ...   
4                0.008735       0.000625  0.014364       0.253022  ...   
...                   ...            ...       ...            ...  ...   
17738            0.007656       0.000552  0.000478       0.004078  ...   
17739            0.130170       0.013863  0.016706       0.000000  ...   
17740            0.002473       0.000000  2.024262       0.998057  ...   
17741            0.002955       0.002310  0.000000       0.431139  ...   
17742            0.015221       0.071824  0.023428       1.037052  ...   

       feelings  danceability  loudness  acousticness  instrumentalness  \
0      0.001021      0.673433  0.753102      0.002560          0.001046   
1      0.001697      0.690740  0.678925      0.785480          0.001009   
2      0.000000      0.186294  0.404628      0.890527          0.060886   
3      0.067061      0.499643  0.685085      0.640129          0.163850   
4      0.000000      0.407141  0.616982      0.030576          0.099289   
...         ...           ...       ...           ...               ...   
17738  0.265363      0.699730  0.753779      0.510676          0.000624   
17739  0.001289      0.758641  0.716034      0.361842          0.000000   
17740  0.003411      0.512652  0.732854      0.017187          0.491014   
17741  0.000000      0.594225  0.754684      0.005137          0.000091   
17742  0.053245      0.465397  0.735680      0.649489          0.099289   

        valence     energy       age  genre  topic  
0      0.040567  48.364265  0.085714      4    2.0  
1      0.743203  28.200609  0.828571      1    7.0  
2      0.093003  13.145639  0.728571      4    5.0  
3      0.648084  62.663152  0.228571      0    5.0  
4      0.524999  48.641741  0.400000      1    1.0  
...         ...        ...       ...    ...    ...  
17738  0.271493  74.876372  0.128571      4    3.0  
17739  0.915961  50.097257  0.257143      5    3.0  
17740  0.606948  92.972488  0.542857      0    6.0  
17741  0.456820  74.079139  0.557143      4    2.0  
17742  0.466926  54.085364  0.400000      4    7.0  

[17743 rows x 27 columns]

In [10]:
#Checking null values
data.describe()

id  release_date        dating      violence    world/life  \
count  17743.000000  17743.000000  17743.000000  17743.000000  17743.000000   
mean    8871.000000   1989.950290      0.044267      0.145387      0.148644   
std     5122.107249     18.158634      0.154204      0.219559      0.214734   
min        0.000000   1950.000000      0.000000      0.000000      0.000000   
25%     4435.500000   1976.000000      0.000489      0.001584      0.001876   
50%     8871.000000   1990.000000      0.001732      0.005458      0.044303   
75%    13306.500000   2006.000000      0.020284      0.221194      0.218735   
max    17742.000000   2019.000000      1.000000      1.000000      1.000000   

         night/time  shake the audience  family/gospel      romantic  \
count  17743.000000        17743.000000   17743.000000  17743.000000   
mean       0.078145            0.042176       0.044730      0.695758   
std        0.175812            0.154612       0.153750      1.727337   
min        0.000000            0.000000       0.000000      0.000000   
25%        0.000771            0.000606       0.001072      0.006831   
50%        0.002566            0.001884       0.002793      0.023584   
75%        0.078145            0.021764       0.027136      0.615776   
max        1.000000            1.000000       1.000000     10.000000   

       communication  ...      feelings  danceability      loudness  \
count   17743.000000  ...  17743.000000  17743.000000  17743.000000   
mean        1.037052  ...      0.053245      0.547723      0.674296   
std         1.749357  ...      0.158942      0.184529      0.131324   
min         0.000000  ...      0.000000      0.000000      0.000000   
25%         0.016104  ...      0.000718      0.433276      0.609524   
50%         0.055749  ...      0.002248      0.547723      0.683205   
75%         1.440751  ...      0.043211      0.666664      0.758184   
max        10.000000  ...      1.000000      1.000000      1.000000   

       acousticness  instrumentalness       valence        energy  \
count  17743.000000      17743.000000  17743.000000  17743.000000   
mean       0.361842          0.099289      0.524999     55.966998   
std        0.330021          0.239817      0.258231     25.218784   
min        0.000000          0.000000      0.000000      0.000000   
25%        0.045411          0.000044      0.321610     36.843080   
50%        0.290429          0.001234      0.524999     55.966998   
75%        0.655972          0.029335      0.730723     76.485258   
max        1.000000          1.000000      1.000000    100.000000   

                age         genre         topic  
count  17743.000000  17743.000000  17743.000000  
mean       0.437873      2.946965      4.528659  
std        0.259731      2.036571      1.964244  
min        0.014286      0.000000      0.000000  
25%        0.214286      1.000000      3.000000  
50%        0.437873      3.000000      5.000000  
75%        0.642857      4.000000      6.000000  
max        1.000000      6.000000      7.000000  

[8 rows x 27 columns]

In [11]:
#Splitting data into dependent and independent variables
data_x = data.drop(['id','genre'], axis = 1)              #Dropping unimportant columns to form X
X = data_x.values
y = data.loc[:, 'genre'].values

In [12]:
#Splitting data into train and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [13]:
print("Shape of X_train: ", X_train.shape )  #X_train.shape
print("Shape of X_test: ", X_test.shape )  #X_test.shape
print("Shape of y_train: ", y_train.shape )  #y_train.shape
print("Shape of y_test", y_test.shape )  #y_test.shape

Shape of X_train:  (14194, 25)
Shape of X_test:  (3549, 25)
Shape of y_train:  (14194,)
Shape of y_test (3549,)


In [14]:
#Standardisation
from sklearn.preprocessing import StandardScaler    
st_x = StandardScaler()    
X_train = st_x.fit_transform(X_train)    
X_test = st_x.transform(X_test)

In [15]:
#K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=33, metric='minkowski', p=2 )
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=33)

In [16]:
#Predicting result
y_pred = classifier.predict(X_test)
y_pred

array([4, 3, 0, ..., 1, 4, 5], dtype=int64)

In [17]:
#Checking Accuracy
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred)) 

0.3722175260636799
              precision    recall  f1-score   support

           0       0.37      0.16      0.22       604
           1       0.34      0.59      0.43       657
           2       0.41      0.38      0.40       120
           3       0.51      0.30      0.38       454
           4       0.36      0.44      0.40       890
           5       0.41      0.37      0.39       327
           6       0.36      0.29      0.32       497

    accuracy                           0.37      3549
   macro avg       0.39      0.36      0.36      3549
weighted avg       0.38      0.37      0.36      3549

[[ 96 186   4  43 160  35  80]
 [ 37 388  13  18 152  31  18]
 [  5   9  46   5  30  22   3]
 [ 36 132   7 138  93  26  22]
 [ 41 261  17  27 390  40 114]
 [ 14  64  15  12  87 120  15]
 [ 33  98  10  27 164  22 143]]


In [18]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1000, random_state=42)

In [19]:
#Predicting result
y_pred = classifier.predict(X_test)
y_pred

array([4, 3, 6, ..., 1, 4, 2], dtype=int64)

In [20]:
#Printing Result
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred)) 

0.4161735700197239
              precision    recall  f1-score   support

           0       0.35      0.18      0.23       604
           1       0.40      0.58      0.47       657
           2       0.53      0.43      0.48       120
           3       0.50      0.39      0.44       454
           4       0.40      0.50      0.45       890
           5       0.45      0.48      0.47       327
           6       0.41      0.31      0.36       497

    accuracy                           0.42      3549
   macro avg       0.44      0.41      0.41      3549
weighted avg       0.42      0.42      0.40      3549

[[106 146   2  54 179  46  71]
 [ 41 378   7  31 157  28  15]
 [  3   7  52   6  26  21   5]
 [ 54  98   5 179  74  28  16]
 [ 46 192  16  45 449  39 103]
 [ 11  53  12  17  67 157  10]
 [ 43  68   4  24 174  28 156]]


In [21]:
test_data

id  release_date    dating  violence  world/life  night/time  \
0     17743        1957.0  0.001244  0.002364    0.000000         NaN   
1     17744        2001.0  0.000000  0.051242    0.199419    0.001062   
2     17745        1990.0  0.000000  0.023786    0.102565    0.000536   
3     17746        1969.0  0.000000  0.411715    0.359957    0.097388   
4     17747        1988.0  0.003277  0.004134    0.137217    0.063368   
...     ...           ...       ...       ...         ...         ...   
5909  23652        1974.0  0.002062  0.001801    0.001365    0.000903   
5910  23653        2006.0  0.003188  0.732295    0.004205    0.000322   
5911  23654        2003.0  0.001259  0.372024    0.097466         NaN   
5912  23655        1992.0  0.001551       NaN    0.000881    0.000000   
5913  23656        2019.0  0.015063  0.117867    0.002405    0.694476   

      shake the audience  family/gospel  romantic  communication  ...  \
0                    NaN       0.026626  0.443483       0.011975  ...   
1               0.001045       0.048439  0.000000       0.013062  ...   
2               0.000563       0.002034  0.017012       1.464849  ...   
3               0.001173       0.000000  0.000436       0.014727  ...   
4               0.044243       0.004400  0.019911       0.026922  ...   
...                  ...            ...       ...            ...  ...   
5909            0.000000       0.000941  0.005743       2.698545  ...   
5910            0.002206       0.003893  0.019414       0.011939  ...   
5911            0.002669       0.001556  0.017121       0.023710  ...   
5912            0.003130       0.001987  0.011560       0.023142  ...   
5913            0.026155       0.001627  0.016157       0.022558  ...   

       sadness  feelings  danceability  loudness  acousticness  \
0     0.002852  0.001754      0.658367  0.535733      0.622990   
1     0.000000  0.027309      0.664157  0.822572      0.191146   
2          NaN  0.025867      0.777592  0.675527      0.067292   
3     0.112646  0.000000      0.938841  0.721391      0.432133   
4     0.002433  0.087650      0.272349  0.387426      0.863575   
...        ...       ...           ...       ...           ...   
5909  0.000502  0.294860      0.441910  0.584495      0.403728   
5910  0.004113  0.004088      0.480442  0.779129      0.000000   
5911  0.028899  0.002258      0.528494  0.792078      0.000945   
5912  0.540026  0.000000      0.358765  0.491650      0.771114   
5913  0.002129  0.000820      0.572477  0.817140      0.017730   

      instrumentalness   valence     energy       age  topic  
0             0.000000  0.813143  42.492736  0.900000    3.0  
1             0.000000  0.589410  82.068773  0.271429    3.0  
2             0.001393  0.581687  47.503369       NaN    3.0  
3                  NaN  0.976364  51.612354  0.728571    6.0  
4             0.779461  0.010007   7.395857  0.457143    1.0  
...                ...       ...        ...       ...    ...  
5909          0.055296  0.791879  44.707269  0.657143    0.0  
5910          0.814137  0.063422  98.312712  0.200000    6.0  
5911          0.422318  0.299094  79.676407       NaN    6.0  
5912          0.000000  0.310226  20.122308  0.400000    NaN  
5913          0.000000  0.524905  83.405516  0.014286    2.0  

[5914 rows x 26 columns]

In [22]:
#Pre Processing as done earlier
data = test_data.drop(['id'], axis = 1)              #Dropping id 
data = data.fillna(data.mean())                      #Filling NaN values
X_train = st_x.fit_transform(data)                   #Standardisation


In [23]:
predictions = classifier.predict(X_train)
predictions

array([0, 4, 5, ..., 6, 1, 4], dtype=int64)

In [24]:
test_data['genre'] = predictions

In [25]:
test_data

id  release_date    dating  violence  world/life  night/time  \
0     17743        1957.0  0.001244  0.002364    0.000000         NaN   
1     17744        2001.0  0.000000  0.051242    0.199419    0.001062   
2     17745        1990.0  0.000000  0.023786    0.102565    0.000536   
3     17746        1969.0  0.000000  0.411715    0.359957    0.097388   
4     17747        1988.0  0.003277  0.004134    0.137217    0.063368   
...     ...           ...       ...       ...         ...         ...   
5909  23652        1974.0  0.002062  0.001801    0.001365    0.000903   
5910  23653        2006.0  0.003188  0.732295    0.004205    0.000322   
5911  23654        2003.0  0.001259  0.372024    0.097466         NaN   
5912  23655        1992.0  0.001551       NaN    0.000881    0.000000   
5913  23656        2019.0  0.015063  0.117867    0.002405    0.694476   

      shake the audience  family/gospel  romantic  communication  ...  \
0                    NaN       0.026626  0.443483       0.011975  ...   
1               0.001045       0.048439  0.000000       0.013062  ...   
2               0.000563       0.002034  0.017012       1.464849  ...   
3               0.001173       0.000000  0.000436       0.014727  ...   
4               0.044243       0.004400  0.019911       0.026922  ...   
...                  ...            ...       ...            ...  ...   
5909            0.000000       0.000941  0.005743       2.698545  ...   
5910            0.002206       0.003893  0.019414       0.011939  ...   
5911            0.002669       0.001556  0.017121       0.023710  ...   
5912            0.003130       0.001987  0.011560       0.023142  ...   
5913            0.026155       0.001627  0.016157       0.022558  ...   

      feelings  danceability  loudness  acousticness  instrumentalness  \
0     0.001754      0.658367  0.535733      0.622990          0.000000   
1     0.027309      0.664157  0.822572      0.191146          0.000000   
2     0.025867      0.777592  0.675527      0.067292          0.001393   
3     0.000000      0.938841  0.721391      0.432133               NaN   
4     0.087650      0.272349  0.387426      0.863575          0.779461   
...        ...           ...       ...           ...               ...   
5909  0.294860      0.441910  0.584495      0.403728          0.055296   
5910  0.004088      0.480442  0.779129      0.000000          0.814137   
5911  0.002258      0.528494  0.792078      0.000945          0.422318   
5912  0.000000      0.358765  0.491650      0.771114          0.000000   
5913  0.000820      0.572477  0.817140      0.017730          0.000000   

       valence     energy       age  topic  genre  
0     0.813143  42.492736  0.900000    3.0      0  
1     0.589410  82.068773  0.271429    3.0      4  
2     0.581687  47.503369       NaN    3.0      5  
3     0.976364  51.612354  0.728571    6.0      5  
4     0.010007   7.395857  0.457143    1.0      3  
...        ...        ...       ...    ...    ...  
5909  0.791879  44.707269  0.657143    0.0      1  
5910  0.063422  98.312712  0.200000    6.0      3  
5911  0.299094  79.676407       NaN    6.0      6  
5912  0.310226  20.122308  0.400000    NaN      1  
5913  0.524905  83.405516  0.014286    2.0      4  

[5914 rows x 27 columns]

In [26]:
#Removing columns
test_data.drop(test_data.columns[1:26], axis = 1, inplace = True)

In [27]:
test_data

id  genre
0     17743      0
1     17744      4
2     17745      5
3     17746      5
4     17747      3
...     ...    ...
5909  23652      1
5910  23653      3
5911  23654      6
5912  23655      1
5913  23656      4

[5914 rows x 2 columns]

In [28]:
#Saving data
test_data.to_csv('submission.csv')